server:
  port: 9003
spring:
  application:
    name: feign
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: feign-9003
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
#info信息
info:
  app:
    name: feign-9003
  company:
    name: www.xxx.com
  build:
    artifactId: ${project.artifactId}
    version: ${project.version}